---
- name: Checking and Removing old directories volumes #Need to add handler for data persistancy
  file:
    path: /docker-data/mqtt
    state: absent
  tags:
    - mqtt

- name: Stopping and Removing old container
  docker_container:
    name: mqtt
    image: eclipse-mosquitto
    state: absent
  tags:
    - mqtt

- name: Adding a Mosquitto group to the OS
  group:
    name: mqtt
    gid: 1883
    state: present
  tags:
    - mqtt

- name: Adding a Mosquitto user to the OS
  user:
    name: mqtt
    group: mqtt
    create_home: no
    shell: /usr/bin/false
    uid: 9001
    state: present
  tags:
    - mqtt

- name: Creating MQTT directories volumes
  file:
    path: /docker-data/mqtt/etc
    state: directory
    owner: mqtt
    group: mqtt
    mode: '0755'
  tags:
    - mqtt

- name: Creating MQTT Persistent Data directories to deploy
  file:
    path: /docker-data/mqtt/data
    state: directory
    owner: mqtt
    group: mqtt
    mode: '0755'
  tags:
    - mqtt

- name: Copying mosquitto.conf
  template:
    src: mosquitto.conf
    dest: /docker-data/mqtt/etc/mosquitto.conf
    owner: mqtt
    group: mqtt
    mode: '0644'
  tags:
    - mqtt

- name: Copying mqtt_users
  copy:
    src: mqtt_users
    dest: /docker-data/mqtt/etc/mqtt_users
    owner: mqtt
    group: mqtt
    mode: '0644'
  tags:
    - mqtt

- name: Copying docker-compose
  template:
    src: docker-compose.yml
    dest: /docker-data/mqtt/docker-compose.yml
    mode: '0644'
  tags:
    - mqtt

- name: Run docker-compose up
  docker_compose:
    project_src: /docker-data/mqtt
    build: no
    pull: yes
  tags:
    - mqtt
    